"use client";

import React from "react";
import { Site, Photo } from "../lib/types";
import { Printer, Download, X, Droplets, CheckCircle2, AlertTriangle, ShieldCheck, Calendar, MapPin, Sparkles } from "lucide-react";
import { getReportDownloadUrl } from "../lib/api";

interface ReportModalProps {
  site: Site;
  photos?: Photo[];
  isOpen: boolean;
  onClose: () => void;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  site,
  photos = [],
  isOpen,
  onClose,
}) => {
  if (!isOpen) return null;

  const analysis = site.latest_analysis;
  const isAnomaly = analysis?.overall_status === "anomaly";
  const isConfirmed = analysis?.overall_status === "confirmed";
  const pdfApiUrl = getReportDownloadUrl(site.id);
  const reportDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
  const reportId = `CWI-${(site.site_code || site.id).toUpperCase()}-${new Date().getFullYear()}`;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-[2000] flex items-center justify-center bg-slate-950/60 backdrop-blur-sm p-4 overflow-y-auto">
      <div className="relative w-full max-w-3xl bg-white rounded-2xl border border-slate-200 shadow-2xl flex flex-col my-8 max-h-[90vh] overflow-y-auto">
        {/* Top Control Bar (Hidden on Print) */}
        <div className="no-print sticky top-0 z-20 flex items-center justify-between px-6 py-4 bg-slate-50 border-b border-slate-200">
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold text-slate-700 uppercase tracking-wider">Official Verification Report</span>
            <span className="text-xs font-mono px-2 py-0.5 rounded bg-slate-200 text-slate-700">{reportId}</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-teal-600 hover:bg-teal-700 text-white text-xs font-medium shadow-sm transition-all cursor-pointer"
              title="Print this official report or save as clean PDF"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / Save as PDF</span>
            </button>

            <a
              href={pdfApiUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-slate-300 hover:bg-slate-50 text-slate-700 text-xs font-medium transition-all"
              title="Download direct PDF generated by server"
            >
              <Download className="w-3.5 h-3.5 text-teal-600" />
              <span>Download Raw PDF</span>
            </a>

            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-slate-600 rounded-lg hover:bg-slate-200 transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* ── Printable Official Certificate Body (Printed Only) ───────────── */}
        <div className="printable-certificate p-8 sm:p-10 flex flex-col gap-6 bg-white text-slate-800">
          {/* Official Document Header */}
          <div className="flex items-start justify-between border-b-2 border-teal-600 pb-5">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-xl bg-teal-50 border border-teal-200 flex items-center justify-center text-teal-600">
                <Droplets className="w-7 h-7" />
              </div>
              <div>
                <h1 className="text-xl font-bold tracking-tight text-slate-900">
                  MeerDrushti (नीरदृष्टी)
                </h1>
                <p className="text-xs font-medium text-teal-700">
                  Watershed Intelligence & Satellite Compliance Verification
                </p>
              </div>
            </div>

            <div className="text-right">
              <div className="text-xs font-mono font-bold text-slate-900">{reportId}</div>
              <div className="text-[11px] text-slate-500 mt-0.5">Date: {reportDate}</div>
              <div
                className={`inline-block mt-2 px-2.5 py-0.5 rounded-full text-[11px] font-bold uppercase border ${
                  isAnomaly
                    ? "bg-red-50 border-red-200 text-red-700"
                    : isConfirmed
                    ? "bg-emerald-50 border-emerald-200 text-emerald-700"
                    : "bg-amber-50 border-amber-200 text-amber-700"
                }`}
              >
                {analysis?.overall_status || "Pending Audit"}
              </div>
            </div>
          </div>

          {/* Section 1: Site Given Information */}
          <div className="flex flex-col gap-2.5">
            <h2 className="text-xs font-bold uppercase tracking-wider text-teal-800 flex items-center gap-1.5">
              <MapPin className="w-3.5 h-3.5" />
              <span>1. Site Identification & Metadata</span>
            </h2>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50 p-4 rounded-xl border border-slate-200 text-xs">
              <div>
                <span className="text-[11px] text-slate-500 block">Site Code</span>
                <span className="font-bold font-mono text-slate-900">{site.site_code || site.id}</span>
              </div>
              <div>
                <span className="text-[11px] text-slate-500 block">Coordinates</span>
                <span className="font-mono text-slate-900">{site.lat.toFixed(4)}°N, {site.lon.toFixed(4)}°E</span>
              </div>
              <div>
                <span className="text-[11px] text-slate-500 block">Intervention Type</span>
                <span className="font-semibold capitalize text-teal-800">
                  {(site.activity_type || "Water Conservation").replace(/_/g, " ")}
                </span>
              </div>
              <div>
                <span className="text-[11px] text-slate-500 block">Buffer Radius</span>
                <span className="font-mono text-slate-900">{site.buffer_radius_m || 500} meters</span>
              </div>

              {site.baseline_date && (
                <div>
                  <span className="text-[11px] text-slate-500 block">Baseline Date</span>
                  <span className="font-mono text-slate-700">{site.baseline_date}</span>
                </div>
              )}
              {site.intervention_date && (
                <div>
                  <span className="text-[11px] text-slate-500 block">Intervention Date</span>
                  <span className="font-mono text-slate-700">{site.intervention_date}</span>
                </div>
              )}
              <div className="col-span-2">
                <span className="text-[11px] text-slate-500 block">Description</span>
                <span className="text-slate-700">{site.description || "Monitored watershed intervention site"}</span>
              </div>
            </div>
          </div>

          {/* Section 2: Health Score & Satellite Telemetry */}
          <div className="flex flex-col gap-2.5">
            <h2 className="text-xs font-bold uppercase tracking-wider text-teal-800 flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5" />
              <span>2. Satellite Spectral Telemetry (Sentinel-2 L2A)</span>
            </h2>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {/* Score Box */}
              <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 flex flex-col justify-between">
                <span className="text-[11px] font-medium text-slate-500">Watershed Health Score</span>
                <div className="flex items-baseline gap-2 my-2">
                  <span className="text-3xl font-extrabold font-mono text-slate-900">
                    {analysis?.health_score !== undefined && analysis?.health_score !== null ? analysis.health_score : "--"}
                  </span>
                  <span className="text-xs text-slate-500 font-mono">/ 100</span>
                </div>
                <div className="text-[11px] font-bold text-teal-700">
                  Grade {analysis?.health_grade || "--"}
                </div>
              </div>

              {/* NDVI Delta */}
              <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 flex flex-col justify-between">
                <span className="text-[11px] font-medium text-slate-500">Vegetation Index (NDVI)</span>
                <div className="my-2">
                  <div className="text-xl font-bold font-mono text-emerald-700">
                    {analysis?.delta_ndvi !== undefined && analysis?.delta_ndvi !== null
                      ? `${analysis.delta_ndvi >= 0 ? "+" : ""}${analysis.delta_ndvi.toFixed(3)}`
                      : `${analysis?.ndvi_tnow?.toFixed(3) || "--"}`}
                  </div>
                  <span className="text-[10px] text-slate-500">
                    {analysis?.mode === "full" ? "Change from baseline" : "Current snapshot"}
                  </span>
                </div>
                <div className="text-[11px] text-slate-600 font-mono">
                  {analysis?.ndvi_t0 != null ? `${analysis.ndvi_t0.toFixed(3)} → ${analysis.ndvi_tnow?.toFixed(3)}` : "10m resolution"}
                </div>
              </div>

              {/* NDWI Delta */}
              <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 flex flex-col justify-between">
                <span className="text-[11px] font-medium text-slate-500">Moisture / Water Index (NDWI)</span>
                <div className="my-2">
                  <div className="text-xl font-bold font-mono text-sky-700">
                    {analysis?.delta_ndwi !== undefined && analysis?.delta_ndwi !== null
                      ? `${analysis.delta_ndwi >= 0 ? "+" : ""}${analysis.delta_ndwi.toFixed(3)}`
                      : `${analysis?.ndwi_tnow?.toFixed(3) || "--"}`}
                  </div>
                  <span className="text-[10px] text-slate-500">
                    {analysis?.mode === "full" ? "Change from baseline" : "Current snapshot"}
                  </span>
                </div>
                <div className="text-[11px] text-slate-600 font-mono">
                  {analysis?.ndwi_t0 != null ? `${analysis.ndwi_t0.toFixed(3)} → ${analysis.ndwi_tnow?.toFixed(3)}` : "10m resolution"}
                </div>
              </div>
            </div>
          </div>

          {/* Section 3: Multi-Modal Cross-Validation Audit */}
          <div className="flex flex-col gap-2.5">
            <h2 className="text-xs font-bold uppercase tracking-wider text-teal-800 flex items-center gap-1.5">
              <ShieldCheck className="w-3.5 h-3.5" />
              <span>3. Cross-Validation Audit Checklist</span>
            </h2>

            <div className="border border-slate-200 rounded-xl overflow-hidden divide-y divide-slate-200 text-xs">
              <div className="p-3 bg-slate-50 flex items-center justify-between">
                <span className="font-medium text-slate-700">Satellite Telemetry Agreement</span>
                <span className="font-bold font-mono text-emerald-700 flex items-center gap-1">
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  <span>{analysis?.satellite_agreement ? "CONFIRMED" : "INCONCLUSIVE"}</span>
                </span>
              </div>

              <div className="p-3 bg-slate-50 flex items-center justify-between">
                <span className="font-medium text-slate-700">Field Photo AI Classification</span>
                <span className="font-bold font-mono text-slate-700">
                  {analysis?.photo_agreement === true ? "MATCHED (OpenCLIP)" : analysis?.photo_agreement === false ? "CONTRADICTED" : "NOT REQUIRED"}
                </span>
              </div>

              {analysis?.flags && analysis.flags.length > 0 && (
                <div className="p-3 bg-red-50/70 border-l-4 border-red-500">
                  <span className="font-bold text-red-800 block mb-1">Flagged Anomalies:</span>
                  <ul className="list-disc list-inside space-y-0.5 text-red-700 text-[11px]">
                    {analysis.flags.map((f, i) => (
                      <li key={i}>{f}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </div>

          {/* Section 4: Photo Evidence (if any) */}
          {photos && photos.length > 0 && (
            <div className="flex flex-col gap-2.5">
              <h2 className="text-xs font-bold uppercase tracking-wider text-teal-800">
                4. Ground Truth Evidence Photos ({photos.length})
              </h2>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
                {photos.slice(0, 3).map((p, idx) => (
                  <div key={idx} className="border border-slate-200 rounded-lg p-2 bg-slate-50 text-[10px]">
                    {p.public_url && (
                      <img
                        src={p.public_url}
                        alt="Field verification"
                        className="w-full h-24 object-cover rounded mb-1.5 border border-slate-200"
                      />
                    )}
                    <div className="font-bold text-slate-800 capitalize">
                      {(p.predicted_class || "photo").replace(/_/g, " ")}
                    </div>
                    {p.classification_confidence && (
                      <div className="text-slate-500 font-mono">
                        Confidence: {(p.classification_confidence * 100).toFixed(1)}%
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Official Verification Seal & Footer */}
          <div className="mt-4 pt-4 border-t border-slate-200 flex flex-col sm:flex-row items-center justify-between gap-3 text-[11px] text-slate-500">
            <div>
              <span className="font-semibold text-slate-700">MeerDrushti (नीरदृष्टी) Verification Authority</span>
              <div>Powered by Copernicus Sentinel-2 L2A & OpenCLIP Zero-Shot ML</div>
            </div>
            <div className="font-mono text-right text-[10px]">
              SHA-256 Validated • Authenticated Dashboard Output
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
